version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-CU10-ubuntu-22.04
    container_name: inventory-system-local-sql-server
    restart: always
    environment:
      SA_PASSWORD: "Strongpwd123_"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - inventory_system_sql_data:/var/opt/mssql

volumes:
  inventory_system_sql_data: